# Branches that trigger a build on commit
trigger:
  - master
  - 2.9.x

variables:
  - name: _TeamName
    value: Roslyn
  - name: _DotNetArtifactsCategory
    value: .NETCore

stages:
- stage: build
  displayName: Build
  jobs:
  - template: /eng/common/templates/jobs/jobs.yml
    parameters:
      enableMicrobuild: true
      enablePublishBuildArtifacts: true
      enablePublishBuildAssets: true
      enablePublishUsingPipelines: true
      enableTelemetry: true
      jobs:
      - job: Signed_Build
        pool:
          name: NetCoreInternal-Pool
          demands: BuildPool.Windows.10.Amd64.VS2019
        variables:
          - group: DotNet-Blob-Feed
          - group: Publish-Build-Assets
          - name: BuildConfiguration
            value: Release
        steps:
        - checkout: self
          clean: true
        - script: eng\common\CIBuild.cmd 
                    -configuration $(BuildConfiguration)
                    /p:OfficialBuildId=$(BUILD.BUILDNUMBER)
                    /p:DotNetSignType=$(SignType)
                    /p:DotNetSymbolServerTokenMsdl=$(microsoft-symbol-server-pat)
                    /p:DotNetSymbolServerTokenSymWeb=$(symweb-symbol-server-pat)
                    /p:PublishToSymbolServer=true
                    /p:DotNetPublishToBlobFeed=true
                    /p:DotNetPublishBlobFeedKey=$(dotnetfeed-storage-access-key-1)
                    /p:DotNetPublishBlobFeedUrl=https://dotnetfeed.blob.core.windows.net/dotnet-core/index.json
                    /p:DotNetArtifactsCategory=$(_DotNetArtifactsCategory)
                    /p:DotnetPublishUsingPipelines=true
          displayName: Build and Test

        # - task: NuGetPublisher@0
        #   displayName: Publish NuGet Packages to MyGet
        #   inputs:
        #     searchPattern: 'artifacts\packages\$(BuildConfiguration)\Shipping\*.nupkg'
        #     connectedServiceName: 'RoslynAnalyzers NuGet feed'
        #     nuGetVersion: 4.0.0.2283
        #   condition: succeeded()

        - task: PublishBuildArtifacts@1
          displayName: Publish Logs
          inputs:
            PathtoPublish: '$(Build.SourcesDirectory)\artifacts\log\$(BuildConfiguration)'
            ArtifactName: 'Logs'
          continueOnError: true
          condition: not(succeeded())

        - task: PublishTestResults@2
          displayName: Publish Test Results
          inputs:
            testRunner: XUnit
            testResultsFiles: 'artifacts/TestResults/$(BuildConfiguration)/*.xml'
            mergeTestResults: true
            testRunTitle: 'Unit Tests'
          condition: always()

        # Archive NuGet packages to DevOps.
        - task: PublishBuildArtifacts@1
          displayName: Publish Artifact Packages
          inputs:
            PathtoPublish: 'artifacts\packages\$(BuildConfiguration)'
            ArtifactName: 'Packages'
          condition: succeeded()

        # Archive VSIX packages to DevOps.
        - task: PublishBuildArtifacts@1
          displayName: Publish Artifact VSIXes
          inputs:
            PathtoPublish: 'artifacts\VSSetup\$(BuildConfiguration)'
            ArtifactName: 'VSIXes'
          condition: succeeded()

- template: eng\common\templates\post-build\post-build.yml
  parameters:
    enableSourceLinkValidation: true
    enableSigningValidation: true
    enableNugetValidation: true